version: "3"

services:

  helpdesk:
    build:
      context: .
    container_name: helpdesk-app
    image: helpdesk-app:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - helpdesk-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/helpdesk
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_FLYWAY_URL=jdbc:mysql://mysql:3306
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=form

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - helpdesk-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

networks:
  helpdesk-network:

volumes:
  database: